---
- name: install python dev library
  apt: name=python-dev
- name: install packages for pip crypto
  apt: name=libffi-dev
- name: install packages for ssl
  apt: name=libssl-dev
- name: install pip
  apt: name=python-pip
- name: install python virtualenv
  pip: name=virtualenv